version: "3"

services:
  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - /data/temp/jupyter/data:/opt/app/data
    environment:
      - JUPYTER_ENABLE_LAB=yes=yes
    restart: unless-stopped
