[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/afterglow.toml",
    # "~/.config/alacritty/themes/themes/gruvbox_material_medium_light.toml"
]

[terminal]
shell = { program = "/bin/zsh" }

[window]
opacity = 0.9
#blur = true
title = "shell"
dynamic_title = true
decorations = "None"
startup_mode = "Maximized"
padding = { x = 5, y = 0 }

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 18
[font.bold]
family = "Fira Code"
style = "Bold"
[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"
[font.italic]
family = "Fira Code"
style = "Italic"
[font.normal]
family = "Fira Code"
style = "Regular"

#光标
[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = "None"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
# action = "Copy"  # conficts with command
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Alt|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://|www)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[keyboard]
bindings = [
    { key = "P", mods = "Alt|Shift", mode = "~Alt", action = "ToggleViMode" } # switch vi mode
]
