version: "2.1"
services:
  plex:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - 5000:80
    volumes:
      - ./config/config.json:/config/settings.json
      - ./config/filebrowser.db:/database/filebrowser.db
      - ./data:/srv
    restart: unless-stopped