version: "3"

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:80"
    volumes:
      - /data/temp/swagger:/foo
    environment:
      - SWAGGER_JSON=/foo/swagger.json
    restart: unless-stopped

# docker run --rm -p 8080:8080 -e SWAGGER_JSON=/foo/swagger.json -v /bar:/foo swaggerapi/swagger-ui
